batch_size: 1
steps: 4
sampler_name: DDIM / Euler A
seed: 3841338856
size:
  width: 704
  height: 512
model: flux1-schnell
vae: ae.sft
clips:
  clip_name1: f5xxl_fp8_e4m3fn.safetensors
  clip_name2: clip_l.safetensors
prompt: modern living room, few plants, decoration, by James McDonald and Joarc Architects, home, interior, octane render, deviantart, greg rutkowski, cinematic, key art, hyperrealism, sun light, sunrays, canon eos c 3 0 0, ƒ 1. 8, 3 5 mm, 8 k, medium - format print