batch_size: 1
steps: 4
sampler_name: Euler
seed: 149792673458055
size:
  width: 512
  height: 768
model: flux1-schnell
vae: ae.sft
clips:
  clip_name1: f5xxl_fp8_e4m3fn.safetensors
  clip_name2: clip_l.safetensors
prompt: racoon in a police uniform, animal wearing a uniform, anthro, very cute kid's film character, disney pixar zootopia character concept artwork, 3d concept, detailed fur, high detail iconic character for upcoming film, trending on artstation, character design, 3 d artistic render, highly detailed, octane, blender, cartoon, shadows, lighting
