batch_size: 1
cfg_scale: 7.5
ddim_eta: 0
ddim_steps: 70
height: 512
n_iter: 1
prompt: assassin, cyberpunk, cyberpsycho, photorealistic, ultra detailed, harsh neon
  lights, octane, bokeh, cyber, cyberpunk city, feature, 8k
sampler_name: DDIM
seed: 666262964
target: txt2img
toggles:
- 0
- 1
- 3
- 4
- 5
- 6
width: 512
