batch_size: 1
cfg_scale: 7.5
ddim_eta: 0
ddim_steps: 70
height: 512
n_iter: 1
prompt: portrait of a female cyberpunk android, cyberpunk, in heavy raining futuristic 
  tokyo rooftop cyberpunk night, sci-fi, fantasy, intricate, very very beautiful,
  elegant, neon light, highly detailed, digital painting, artstation, concept art, 
  soft light, hdri, smooth, sharp focus, illustration, art by tian zi and craig 
  mullins and wlop and alphonse mucha
sampler_name: DDIM
seed: 1556409771
target: txt2img
toggles:
- 0
- 1
- 3
- 4
- 5
- 6
width: 512
