batch_size: 1
steps: 4
sampler_name: Euler
seed: 381396986945421
size:
  width: 512
  height: 768
model: flux1-schnell
vae: ae.sft
clips:
  clip_name1: f5xxl_fp8_e4m3fn.safetensors
  clip_name2: clip_l.safetensors
prompt: wakandan warrior wearing moonknight mcu style armor, ultra realistic, concept art, intricate details, eerie, horror, highly detailed, photorealistic, octane render,  8 k, unreal engine, sharp focus, volumetric lighting unreal engine. art by artgerm and greg rutkowski and alphonse mucha
