batch_size: 1
cfg_scale: 7.5
ddim_eta: 0
ddim_steps: 50
height: 512
n_iter: 12
prompt: 'epic concept art by barlowe wayne, ruan jia and greg rutkowski. a winding
  road to fantasy palace, forest with small river, camp fire with men, light effect.
  volumetric light, 3d, ultra clear detailed. octane render. 8k. dark green, light
  grey blue and golden colour scheme. '
sampler_name: DDIM
seed: 1679638567
target: txt2img
toggles:
- 1
- 2
- 3
- 4
- 5
width: 704
