batch_size: 1
steps: 4
sampler_name: Euler
seed: 1098515614782141
size:
  width: 512
  height: 768
model: flux1-schnell
vae: ae.sft
clips:
  clip_name1: f5xxl_fp8_e4m3fn.safetensors
  clip_name2: clip_l.safetensors
prompt: magestic mountains, birds in the sky, waterfall close shot 35 mm, realism, octane render, 8 k, exploration, cinematic, trending on artstation, 35 mm camera, unreal engine, hyper detailed, photo - realistic maximum detail, volumetric light, moody cinematic epic concept art, realistic matte painting, hyper photorealistic, epic, trending on artstation, movie concept art, cinematic composition, ultra - detailed, realistic,
