batch_size: 1
cfg_scale: 7.5
ddim_eta: 0
ddim_steps: 250
height: 704
n_iter: 1
prompt: tom hardy with tight t-shirt, bust portrait, photograph, depth of field. bokeh.
  colored, moody light, golden hour. by Dan Winters, Russell James, Steve McCurry.
  centered. extremely detailed. Nikon D850, (35mm&#124;50mm&#124;85mm). award winning
  photography.
sampler_name: DDIM
seed: 1305888856
target: txt2img
toggles:
- 0
- 1
- 3
- 4
- 5
- 6
width: 512
