batch_size: 1
cfg_scale: 7.5
ddim_eta: 0
ddim_steps: 50
height: 512
n_iter: 1
prompt: 'vibrant food photo of a steak with backed potatoes on a plate, depth of field.
  bokeh. soft light. by Yasmin Albatoul, Harry Fayt. centered. extremely detailed.
  Nikon D850 85mm. award winning photography. '
sampler_name: DDIM
seed: 1275536682
target: txt2img
toggles:
- 0
- 1
- 2
- 3
- 4
- 5
width: 512
