batch_size: 1
steps: 4
sampler_name: Euler
seed: 484934626222100
size:
  width: 512
  height: 768
model: flux1-schnell
vae: ae.sft
clips:
  clip_name1: f5xxl_fp8_e4m3fn.safetensors
  clip_name2: clip_l.safetensors
prompt: closeup photo of a dinner plate, chef level, expensive, luxurious, focus, soft light, by Yasmin Albatoul, Harry Fayt, centered, extremely detailed, Nikon D850 85mm, award winning photography