batch_size: 1
cfg_scale: 7.5
ddim_eta: 0
ddim_steps: 70
height: 512
n_iter: 1
prompt: white house, postapocalyptic, overgrown with plant life and ivy, fog, animals,
  birds, deer, bunny, artgerm, yoshitaka amano, gothic interior, 8k, octane render,
  unreal engine
sampler_name: DDIM
seed: 3282173003
target: txt2img
toggles:
- 0
- 1
- 2
- 3
- 4
- 5
width: 704
