batch_size: 1
cfg_scale: 7.5
ddim_eta: 0
ddim_steps: 70
height: 512
n_iter: 4
prompt: metropole city, sketch, drawing, detailed, pencil, black and white by Adonna
  Khare, Paul Cadden, Pierre-Yves Riveau
sampler_name: DDIM
seed: 820781051
target: txt2img
toggles:
- 1
- 2
- 3
- 4
- 5
width: 512
