batch_size: 1
cfg_scale: 7.5
ddim_eta: 0
ddim_steps: 70
height: 512
n_iter: 9
prompt: 'epic space, planets, stars, by Andrew McCarthy, Navaneeth Unnikrishnan, Manuel
  Dietrich, photo realistic, 8 k, cinematic lighting, hd, atmospheric, hyperdetailed,
  trending on artstation, deviantart, photography, glow effect '
sampler_name: DDIM
seed: 3963616006
target: txt2img
toggles:
- 1
- 2
- 3
- 4
- 5
width: 512
